// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function UpsertAccount(arg1) {
  return window['go']['main']['App']['UpsertAccount'](arg1);
}
